title: Sumanth Guduguntla # your name (or website title) here
logo: "/images/model image.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A result-oriented professional with experience in Investment Banking/Financial Services domains with working knowledge of SQL, Python, Tableau, R, MS Office Suite, and VBA. Passionate for identifying insights and opportunities and helping business & product teams make informed data-driven decisions. Have experience working with cross-functional teams and learning things on-the-go, while taking up projects on my own. 
  <br><br>
  <a href="https://www.linkedin.com/in/sumanth-guduguntla/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
